Improve wording in note helpers' rename note command
NotePlan/plugins pull request #526
Opened 2024-02-08 23:40 UTC by leomeloxp

Fix #513

2024-02-08 23:42 UTC, leomeloxp commented on jgclark.NoteHelpers/src/helpers/renameNotes.js
> +  Would you like to rename "${currentFilename}" to match the note title "${title}"?
The fix to the issue highlighted raised by @ariccb.

2024-02-08 23:51 UTC, leomeloxp commented on jgclark.NoteHelpers/plugin.json
> +    },
See code below for implementation details. This adds a new command for setting the filename (excluding extension) as the note title.

<details><summary>Filename</summary>
<img width="254" alt="SCR-20240208-umum" src="https://github.com/NotePlan/plugins/assets/266852/13a6e568-321d-476f-8d91-f6217d8aa8e9">
</details> 

<details><summary>Noteplan command</summary>
<img width="739" alt="SCR-20240208-umiv" src="https://github.com/NotePlan/plugins/assets/266852/bd3c36b4-2d4c-49dd-9df3-fddd8f6cbba9">
</details> 

<details><summary>Confirmation prompt</summary>
<img width="308" alt="SCR-20240208-umrq" src="https://github.com/NotePlan/plugins/assets/266852/a5134869-95a3-4099-990f-82519d90fdce">
</details>

2024-02-09 11:04 UTC, jgclark commented on jgclark.NoteHelpers/src/helpers/makeNoteTitleMatchFilename.js
> +    await showMessage('This command does not support calendar notes.')
Or "Sorry: calendar notes cannot be renamed."

2024-02-09 11:07 UTC, jgclark commented on jgclark.NoteHelpers/src/lib/commands/renameInconsistentNames.js
> +      `Would you like to be prompted before renaming each of these notes filenames?
```suggestion
      `Would you like to be prompted before renaming each of these note filenames?
```

2024-02-09 11:08 UTC, jgclark commented on jgclark.NoteHelpers/src/helpers/makeNoteTitleMatchFilename.js
> +    await showMessage('This command does not support calendar notes.')
```suggestion
    await showMessage('Sorry: calendar notes cannot be renamed.')
```

2024-02-09 11:11 UTC, jgclark commented on jgclark.NoteHelpers/src/helpers/renameNotes.js
I think somewhere in here you need to check for cases where there are valid title characters that aren't valid filename characters. I can think of at least `:`, but there may be others. And you may want to defeat on leading `.` as well.

2024-02-09 11:12 UTC, jgclark requested changes
Good work. I've made a few small comments, only one of which (about invalid characters) is important.
I will have to look when I'm at my desktop to see what the test problem is.

2024-02-12 22:18 UTC, leomeloxp commented on jgclark.NoteHelpers/src/helpers/renameNotes.js
Added a function to check for it and report an error to the user if any invalid characters are found.

I didn't really read too much into which characters should be added to the list but I at least there is something in there.

2024-02-12 23:13 UTC, jgclark approved these changes

2024-02-12 23:13 UTC, merged