Add support for tracking checklist progress
NotePlan/plugins pull request #533
Opened 2024-02-28 18:23 UTC by aaronpoweruser

- Adds a new setting for a reference note to compare.
- Marks any checked task as complete for the day.

2024-02-28 21:52 UTC, jgclark commented
Firstly, well done for understanding the quite complex code well enough to make any addition. It has evolved significantly over the years, and so the design may rightly feel a bit odd. Secondly, I hope this means my commenting was in pretty good shape.
Thirdly, this feels sufficiently different from the other ways that summaries work that it will definitely need a new subsection in the README before it's released. I think a before and after example would be good.

2024-04-15 19:04 UTC, aaronpoweruser commented
@jgclark updated the documentation, any other changes?

2024-04-17 20:22 UTC, jgclark commented on jgclark.Summaries/src/todayProgress.js
> +      GOChecklistRefNote: string,
This is an error. You probably mean ''.

2024-04-17 20:23 UTC, jgclark commented on jgclark.Summaries/src/progress.js
> +        GOChecklistRefNote: config.progressChecklistReferenceNote,
This doesn't look ideal, as it breaks the clear pattern above. 
What you want is to add the ability to pass this in as a parameter, like all the others, unless there's a good reason it doesn't make sense.

2024-04-17 20:24 UTC, jgclark requested changes
Please see just 2 lines where I think changes are needed.
I've made a few typo corrections in the README.

2024-04-18 23:55 UTC, jgclark commented
Well done again, @aaronpoweruser. 
Good news:  I've asked Eduard to give you write permission for this repo, and he says he's now done so.
So please enjoy being able to merge and then release this yourself. 
To release use `npc plugin:release jgclark.Dashboard` 
and then add a comment in the Discord channel that's similar to the CHANGELOG entry.

2024-04-20 00:47 UTC, merged